name: Laravel Code Linting (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: fileinfo, xdebug

      - name: Clear Composer Cache
        run: composer clear-cache

      - name: Install Dependencies
        run: composer install --no-progress --prefer-dist

      - name: Check PHP Installation
        run: where.exe php

      - name: Validate Laravel Pint Installation
        run: php vendor/bin/pint --version || echo "Laravel Pint is not installed!"

      - name: Run Laravel Pint
        run: php ./vendor/bin/pint --test
